version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: beautyflow_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: beautyflow
    ports:
      - "5432:5432"
    volumes:
      - beautyflow_data:/var/lib/postgresql/data

volumes:
  beautyflow_data:
